config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'about' => 'pages#about'

  get 'help' => 'pages#help'

  get 'contact' =>  'pages#contact'

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { email.downcase! }
	before_save { username.downcase! }

	validates :full_name, length: { maximum: 25 }, presence: true
	validates :username, length: { maximum: 12 }, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, length: { maximum: 244 }, presence: true,
					  format: { with: VALID_EMAIL_REGEX },
					  uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, length: { minimum: 8}, presence: true

	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
													  BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end
  
  def about
  end

  def help
  end

  def contact
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in user
      redirect_to user
  	else
  		flash.now[:danger] = 'Invalid email/password combination'
  		render 'new'
  	end
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      log_in @user
      flash[:success] = "Welcome to Blogger!"
      redirect_to @user
  	else
  		render 'new'
  	end
  end


  private
  	def user_params
  		params.require(:user).permit(:full_name, :username, :email, :password, :password_confirmation)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title = '')
		base_title = "Blogger"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end		
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	#Logs in the given user.
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user, options = { size: 70 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.full_name, class: "gravatar")
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Blogger", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help",  help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", "#" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Setting", "#" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log In", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

        

app/views/pages/about.html.erb
<% provide :title, "About Us" %>

<h1>About Us</h1>
<p>
	This is the home page for the
	<a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
	sample application.
</p>

app/views/pages/contact.html.erb
<% provide :title, "Contact Us" %>
<h1>Contact Us</h1>
<p>
	This is the home page for the
	<a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
	sample application.
</p>
 

app/views/pages/help.html.erb
<% provide :title, "Help" %>

<h1>Help</h1>
<p>
	This is the home page for the
	<a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
	sample application.
</p>

app/views/pages/home.html.erb
<% provide :title, "Welcome" %>
<div class="center jumbotron">
	<h1>Welcome to Blogger</h1>
	<h2>
		This is the home page for the
		<a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
		sample application.
	</h2>

	<%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
'http://rubyonrails.org/' %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(@user.errors.count, "error") %>
		</div>
	</div>
	<ul>
	<% @user.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>
	</ul>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>
			
			<%= f.label :Full_name %>
			<%= f.text_field :full_name, class: 'form-control' %>

			<%= f.label :Username %>
			<%= f.text_field :username, class: 'form-control' %>

			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control' %>

			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>

			<%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>
	</div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.full_name) %>
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
			<h1>
				<%= gravatar_for @user %>
				<%= @user.full_name %>
			</h1>
		</section>
	</aside>
</div>